/**
 * Conservation Reporting Agent
 *
 * Generates a structured markdown conservation report for the full
 * Gujarat heritage network. In demo mode, uses deterministic templates.
 * In live mode, routes through the IBM Granite proxy.
 */

import type { ConservationReport, RiskLevel } from '../types'
import { HERITAGE_SITES, DEMO_CASES } from '../data/demoData'
import { IS_DEMO_MODE } from './graniteService'

// ─── Deterministic demo report ────────────────────────────────────────────────

function buildMarkdown(report: Omit<ConservationReport, 'markdown'>): string {
  const date = new Date().toLocaleDateString('en-IN', {
    day: 'numeric', month: 'long', year: 'numeric'
  })

  const riskEmoji: Record<RiskLevel, string> = {
    CRITICAL: '🔴', HIGH: '🟠', MODERATE: '🟡', LOW: '🟢'
  }

  let md = `# DHAROHAR AI — Gujarat Heritage Network Conservation Report
**Generated:** ${date} | **Period:** ${report.period}
**Model:** ${report.modelUsed} | **Mode:** ${report.demoMode ? 'Demo AI Mode' : 'IBM Granite Live'}

---

## Executive Summary

${report.networkSummary}

---

## Site-by-Site Conservation Status

`

  for (const s of report.siteReports) {
    const emoji = riskEmoji[s.riskLevel]
    md += `### ${emoji} ${s.siteName}
**Health Score:** ${s.healthScore}/100 | **Risk Level:** ${s.riskLevel}

**Key Issues:**
${s.keyIssues.map((i) => `- ${i}`).join('\n')}

**Recommended Actions:**
${s.recommendedActions.map((a, idx) => `${idx + 1}. ${a}`).join('\n')}

---

`
  }

  md += `## Priority Sites Requiring Immediate Attention

${report.prioritySites.map((s, i) => `${i + 1}. **${s}**`).join('\n')}

---

## Network-Wide Recommendations

${report.overallRecommendations.map((r) => `- ${r}`).join('\n')}

---

*This report was generated by DHAROHAR AI Heritage Guardian using IBM Granite LLM reasoning.*
*AI-assisted preliminary assessment — all critical decisions require professional heritage conservation verification.*
`

  return md
}

function generateDemoReport(): ConservationReport {
  const siteReports = HERITAGE_SITES.map((site) => {
    const cases = DEMO_CASES.filter((c) => c.siteId === site.id)

    const keyIssues =
      cases.length > 0
        ? cases.map((c) => `${c.title} (${c.riskLevel} risk, status: ${c.status.replace(/_/g, ' ')})`)
        : [`Heritage health score at ${site.healthScore}/100 — requires monitoring`]

    const getActions = (riskLevel: RiskLevel): string[] => {
      switch (riskLevel) {
        case 'CRITICAL':
          return [
            'Commission emergency structural assessment within 48 hours',
            'Activate emergency conservation protocol with ASI and INTACH',
            'Install immediate protective shoring where required',
          ]
        case 'HIGH':
          return [
            'Commission expert inspection by qualified heritage conservation professional within 7 days',
            'Implement temporary visitor management protocols at affected zones',
            'Increase monitoring frequency to weekly photographic survey',
          ]
        case 'MODERATE':
          return [
            'Schedule professional condition monitoring visit within 4 weeks',
            'Review visitor management protocols and maintenance schedule',
            'Update photographic baseline documentation',
          ]
        default:
          return [
            'Maintain current monitoring schedule',
            'Document condition at next quarterly survey',
          ]
      }
    }

    return {
      siteId: site.id,
      siteName: site.name,
      healthScore: site.healthScore,
      riskLevel: site.riskLevel,
      keyIssues,
      recommendedActions: getActions(site.riskLevel),
    }
  })

  const avgScore = Math.round(HERITAGE_SITES.reduce((s, h) => s + h.healthScore, 0) / HERITAGE_SITES.length)
  const criticalCount = HERITAGE_SITES.filter((s) => s.riskLevel === 'CRITICAL').length
  const highCount = HERITAGE_SITES.filter((s) => s.riskLevel === 'HIGH').length

  const networkSummary =
    `The Gujarat Heritage Network currently monitors ${HERITAGE_SITES.length} heritage sites with an average Heritage Health Score of ${avgScore}/100. ` +
    `${criticalCount} site${criticalCount !== 1 ? 's are' : ' is'} at CRITICAL risk and ${highCount} site${highCount !== 1 ? 's are' : ' is'} at HIGH risk, ` +
    `requiring immediate conservation attention. The most vulnerable site is ${HERITAGE_SITES.sort((a, b) => a.healthScore - b.healthScore)[0].name} ` +
    `with a health score of ${Math.min(...HERITAGE_SITES.map(s => s.healthScore))}/100. ` +
    `Active conservation cases total ${DEMO_CASES.filter(c => c.status !== 'RESOLVED').length} open incidents across the network. ` +
    `Priority action is required at the Pol Heritage Zone (EMERGENCY status) and Bhadra Fort (INTERVENTION status) within the next 7 days.`

  const prioritySites = HERITAGE_SITES
    .filter((s) => s.riskLevel === 'CRITICAL' || s.riskLevel === 'HIGH')
    .sort((a, b) => a.healthScore - b.healthScore)
    .map((s) => `${s.name} (Score: ${s.healthScore}/100, Risk: ${s.riskLevel})`)

  const overallRecommendations = [
    'Establish monthly multi-stakeholder conservation coordination meeting (AMC, ASI, INTACH, UNESCO India)',
    'Commission network-wide heritage condition survey to update baselines for all sites',
    'Review and reinstate monitoring schedules for all sites with inspection gaps exceeding 6 months',
    'Develop site-specific carrying capacity assessments for high-visitor-pressure sites',
    'Initiate emergency conservation action plan for Pol Heritage Zone — EMERGENCY status requires immediate multi-agency response',
    'Ensure all conservation interventions use heritage-compatible materials and reversible techniques per UNESCO/ASI guidelines',
    'Expand DHAROHAR AI monitoring to include environmental sensor integration for humidity and temperature at moisture-sensitive sites',
  ]

  const report: Omit<ConservationReport, 'markdown'> = {
    id: `report-${Date.now()}`,
    generatedAt: new Date().toISOString(),
    period: `Q1 2024 — ${new Date().toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })}`,
    networkSummary,
    siteReports,
    overallRecommendations,
    prioritySites,
    modelUsed: 'IBM Granite (Demo AI Mode)',
    demoMode: true,
  }

  return { ...report, markdown: buildMarkdown(report) }
}

// ─── Live Granite report ───────────────────────────────────────────────────────

async function generateLiveReport(): Promise<ConservationReport> {
  const sitesSummary = HERITAGE_SITES.map(
    (s) => `${s.name}: Health ${s.healthScore}/100, Risk ${s.riskLevel}, Status ${s.conservationStatus}, Active Alerts ${s.activeAlerts}`
  ).join('\n')

  const casesSummary = DEMO_CASES.slice(0, 5).map(
    (c) => `${c.caseNumber}: ${c.title} (${c.riskLevel}, ${c.status})`
  ).join('\n')

  const prompt = `Generate a professional heritage conservation status report for the Gujarat Heritage Network.

HERITAGE SITES:
${sitesSummary}

ACTIVE CONSERVATION CASES:
${casesSummary}

Write a comprehensive conservation report covering:
1. Executive summary of network health
2. Per-site status with key issues and recommended actions
3. Network-wide priority recommendations
4. Priority sites requiring immediate attention

Format as clear professional report text. Be specific and actionable.`

  const res = await fetch('/api/granite/report', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ prompt }),
  })

  if (!res.ok) throw new Error('Report generation failed')

  const data = await res.json() as { text: string }
  const demo = generateDemoReport()

  return {
    ...demo,
    networkSummary: data.text.slice(0, 600),
    markdown: data.text,
    modelUsed: 'IBM Granite',
    demoMode: false,
  }
}

// ─── Public interface ──────────────────────────────────────────────────────────

export async function generateConservationReport(): Promise<ConservationReport> {
  if (IS_DEMO_MODE) {
    await new Promise((r) => setTimeout(r, 1200))
    return generateDemoReport()
  }

  try {
    return await generateLiveReport()
  } catch (err) {
    console.warn('Live report failed, using demo:', err)
    return generateDemoReport()
  }
}
